name: Check Tag
on:
  workflow_call:

jobs:
  check_tag:
    name: "Check Tag"
    runs-on: ubuntu-latest
    steps:
      - name: Check if tag is valid
        run: |
          if [[ ! $GITHUB_REF_NAME =~ ^v[0-9]+\.[0-9]+\.[0-9]+(-[a-zA-Z0-9]+(\.[0-9]+)?)?$ ]]; then
            echo "Tag value is not valid. Please use a valid tag value."
            exit 1
          fi
