name: Test
on:
  workflow_dispatch:
    inputs:
      platform:
        type: choice
        default: k8s
        description: Choice a platform
        required: true
        options:
          - k8s
          - cops

jobs:
  show-platform:
    uses: ./.github/workflows/printer.yaml
    with:
      PLATFORM: ${{ github.event.inputs.platform }}
