# name: Github Action Teste

# on:
#   workflow_dispatch:
#     inputs:
#       releaseType:
#         description: 'Release Type'
#         required: true
#         default: 'PATCH'
#         type: choice
#         options:
#         - MAJOR
#         - MINOR
#         - PATCH
# #     inputs:
# #       tag:
# #         description: "Tag value"
# #         required: true
# #   release:
# #     types:
# #       - published
# # env:
# #   TAG: ${{ github.event.release.tag_name || github.event.inputs.tag }}
# # jobs:
# #   check-tag:
# #     runs-on: ubuntu-latest
# #     steps:
# #       - name: Check TAG
# #         if: ${{ !startsWith(env.TAG, 'v') }}
# #         uses: actions/github-script@v6
# #         with:
# #           script: |
# #             core.setFailed('Please, select a valid TAG instead branch [ ${{ github.ref_name }} ]')
# #       - name: Display env TAG
# #         run: echo ${{ env.TAG }}

# jobs:
#   update_release:
#     runs-on: ubuntu-latest
#     permissions:
#       contents: write
#     steps:
#       - uses: actions/checkout@v3
#         with:
#           fetch-depth: 0

#       - uses: actions/setup-node@v3
#         with:
#           node-version: 18

#       - name: Update version
#         run: node update-version.js ${{ github.event.inputs.releaseType }}

#       - name: Commit changes
#         run: |
#           git config --global user.email "bruno.monteirodg@gmail.com"
#           git config --global user.name "Edinho Monteiro"
#           git commit -am "feat: update release version"
#           git push origin main

# #   job2:
# #     runs-on: ubuntu-latest
# #     steps:
# #       - name: Display env TAG
# #         run: echo ${{ env.TAG }}
#   # job3:
#   #   runs-on: ubuntu-latest
#   #   env:
#   #     TAG: ${{ env.TAG }}
#   #   steps:
#   #     - name: Display env TAG
#   #       run: echo ${{ env.TAG }}

name: Test
on:
  workflow_dispatch:
    inputs:
      tag_value:
        description: "Tag value"
        required: true
  release:
    types: [published]
env:
  TAG_REF: ${{ github.event.inputs.tag_value || github.ref_name }}

jobs:
  printer:
    name: Print version
    runs-on: ubuntu-latest
    steps:
      - name: print
        run: echo ${{ env.TAG_REF }}
