name: Mixed inputs

on:
  workflow_dispatch:
    inputs:
      name:
        type: choice
        description: Who to greet
        options:
        - monalisa
        - cschleiden
      message:
        required: true
      use-emoji:
        type: boolean
        description: Include 🎉🤣 emojis
      environment:
        type: environment

jobs:
  greet:
    runs-on: ubuntu-latest

    steps:
    - name: Send greeting
      run: echo "${{ github.event.inputs.message }} ${{ fromJSON('["", "🥳"]')[github.event.inputs.use-emoji == 'true'] }} ${{ github.event.inputs.name }}"

    - name: Emoji?
      if: ${{ github.event.inputs.use-emoji == 'true' }}
      run: echo "You chose to use emojis! 🎉🤣"

    - name: Show msg
      run: |
        echo "Message is: ${{ github.event.inputs.message }}"

    - name: Show commit SHA
      env:
        COMMIT_HASH: ${GITHUB_SHA:0:7}
      run: |
        echo "The commit SHA is ${{ github.sha }}"
        echo "The short commit hash is $COMMIT_HASH"
        echo "The short commit hash is ${GITHUB_SHA:0:7}"

