name: Tests

on:
  workflow_dispatch:
  pull_request:
    types:
      - labeled

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  integration-tests:
    name: Integration Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 1

      - name: check if label is correct
        id: check_label
        run: |
          if [[ ! " ${GITHUB_EVENT_LABELS[*]} " =~ " run:integration-tests " ]]; then
            echo ${GITHUB_EVENT_LABELS[*]}
            echo "Label 'run:integration-tests' not found. Skipping integration tests."
            exit 1
          fi

      - run: echo "Running integration tests..."
        # Here you would add the actual commands to run your integration tests

      - name: Remove label
        if: always() # Ensure the label is removed even if tests fail
        uses: actions-ecosystem/action-remove-labels@v1
        with:
          labels: 'run:integration-tests'
